# vim: filetype=dockerfile:

FROM python:3.7

MAINTAINER Mike Margetts <mmargetts@owletcare.com>

WORKDIR /usr/local/src

# Upgrade pip
RUN pip install --upgrade pip

# Install requirements
COPY requirements.txt .
RUN pip install -r requirements.txt
